export default {
	NEWS_RECEIVED: 'NEWS_RECEIVED',
	NEWSITEM_RECEIVED: 'NEWSITEM_RECEIVED',
	NEWSITEM_LOADING: 'NEWSITEM_LOADING',
	USER_REGISTERED: 'USER_REGISTERED',
	USER_LOGGEDIN: 'USER_LOGGEDIN',
	USER_LOGOUT: 'USER_LOGOUT',
	NEWS_ADDCOMMENT: 'NEWS_ADDCOMMENT'
}